---

- hosts: web
  
  vars:
   root_password: 'root'

  tasks:
  - name: installation Mariadb
    dnf:
     name: "{{ item }}"
     state: present
    loop:
     - mariadb
     - python3-PyMySQL
     - mariadb-server
  - name:  Activation Mariadb
    systemd:
     name: mariadb
     state: started
     enabled: yes
